### ISSUE TITLE
Multi-Tenant - Error on adding Role to 2nd Tenant

### ISSUE THREAD

**Issue by 274188A** [radzenhq/radzen-blazor-studio#107]
Exception thrown: System.InvalidOperationException: Role XYZ_ADMIN does not exist.

Blazor Studio (1.9.0)
Visual Studio 2022 (Latest Stable)
SQL Server 2019
Blazor Server with 'CRUD' template
ASP.NET CORE Identity

2 Tenants
1 Role / Tenant
1 User / Role / Tenant

1st role and user added and works.
2nd user can be add but when adding to the role error is thrown.

To Reproduce go to this repo: [https://github.com/274188A/radzen-issue](https://github.com/274188A/radzen-issue)
To set up the same db use the file [here](https://github.com/274188A/radzen-issue/blob/main/dbscript/script.sql).

Select Tenant 'XYZ'
![image](https://user-images.githubusercontent.com/40014477/236800285-bd7163b8-2d3e-4f05-87da-02e26125c6ea.png)

Click User and edit
![image](https://user-images.githubusercontent.com/40014477/236800715-f966ce62-9a42-4ab5-8096-be95fe09ee80.png)
Save with Role
![image](https://user-images.githubusercontent.com/40014477/236800938-6a153289-cdfe-46e0-885e-b7cc925ce230.png)

**Stack Trace**
>System.InvalidOperationException
  HResult=0x80131509
  Message=Role XYZ_ADMIN does not exist.
  Source=Microsoft.AspNetCore.Identity.EntityFrameworkCore
  StackTrace:
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.<AddToRoleAsync>d__34.MoveNext()
   at Microsoft.AspNetCore.Identity.UserManager`1.<AddToRolesAsync>d__106.MoveNext()
   at BugTest.Controllers.ApplicationUsersController.<Patch>d__10.MoveNext() in C:\Users\274188A\source\repos\JUNK\issue\Controllers\ApplicationUsersController.cs:line 117

  This exception was originally thrown at this call stack:
    [External Code]
System.InvalidOperationException
  HResult=0x80131509
  Message=Role XYZ_ADMIN does not exist.
  Source=Microsoft.AspNetCore.Identity.EntityFrameworkCore
  StackTrace:
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.<AddToRoleAsync>d__34.MoveNext()
   at Microsoft.AspNetCore.Identity.UserManager`1.<AddToRolesAsync>d__106.MoveNext()
   at BugTest.Controllers.ApplicationUsersController.<Patch>d__10.MoveNext() in C:\Users\274188A\source\repos\JUNK\issue\Controllers\ApplicationUsersController.cs:line 117

  This exception was originally thrown at this call stack:
    [External Code]
    BugTest.Controllers.ApplicationUsersController.Patch(string, BugTest.Models.ApplicationUser) in ApplicationUsersController.cs

**Comment by 274188A** [comment]
Debugging this a bit more - so **after switching to the `XYZ`** tenant and trying to add the Role to the user I see this:

![image](https://user-images.githubusercontent.com/40014477/236978568-9cc78603-20a9-4a85-92d2-589495a5a29e.png)
So this pic show the tenant being in context is wrong - it should be `XYZ` (not `ABC`).

**Comment by 274188A** [comment]
So I see the GetTenant() function uses the Host address to identify a single unique host.

![image](https://user-images.githubusercontent.com/40014477/236979254-6abe76e5-abbb-44dc-9429-26d970974c74.png)


Both my Tenants run on the same address so here we have the problem

**Comment by 274188A** [comment]
Closing this to ask a related question - the point is the developer must ensure the Tenant Host is a URL and that it's unique to the tenant
