### ISSUE TITLE
Issue during new page creating 

### ISSUE THREAD

**Issue by TomekProdevelopers** [radzenhq/radzen-blazor-studio#11]
Hi,
I have created new Blazor server project. I opened it in RBS and during adding new page there is exception: 
```
System.Collections.Generic.KeyNotFoundException: The given key '{Name}.razor.cshtml' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Radzen.Server.CodeGenerationTemplateGenerator`1.GenerateAsync(ProjectServer server, String outputPath, String name, CancellationToken token) in /Users/korchev/github/radzen-next/Radzen.Server/CodeGeneratorService.cs:line 240
   at Radzen.Server.CodeGenerationService.<>c__DisplayClass5_1.<<Generate>b__0>d.MoveNext() in /Users/korchev/github/radzen-next/Radzen.Server/CodeGeneratorService.cs:line 144
```

**Comment by akorchev** [comment]
Should be fixed in 1.0.0.preview.3 that we just released.

**Comment by basztech** [comment]
Hi Atanas, I have the same issue in preview.3. 
I do like what you have done a lot! Things always break when you give them to users though :)

**Comment by basztech** [comment]
Sorry, not the same issue but similar on creating new page...
`Radzen.Server.CompilationFailedException: error CS1705: Assembly 'Radzen.Server' with identity 'Radzen.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

   at Radzen.Server.ProjectContext.Compile(Compilation compilation, AssemblyLoadContext context) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectContext.cs:line 120
   at Radzen.Server.ProjectServer.CompileTemplate(String fileName, String source, RazorProjectEngine projectEngine, AssemblyLoadContext context) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 805
   at Radzen.Server.ProjectServer.RenderTemplate[T](String path, String content, T model) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 188
   at Radzen.Server.CodeGenerationTemplateGenerator`1.GenerateAsync(ProjectServer server, String outputPath, String name, CancellationToken token) in /Users/korchev/github/radzen-next/Radzen.Server/CodeGeneratorService.cs:line 242
   at Radzen.Server.CodeGenerationService.<>c__DisplayClass5_1.<<Generate>b__0>d.MoveNext() in /Users/korchev/github/radzen-next/Radzen.Server/CodeGeneratorService.cs:line 144`

**Comment by akorchev** [comment]
Should be solved in the latest version. Also make sure your app isn't .NET Core 3.1 as Radzen Blazor Studio does not support it. Let us know if the problem persists after updating to the latest version!
