### ISSUE TITLE
Page creation runtime version message

### ISSUE THREAD

**Issue by basztech** [radzenhq/radzen-blazor-studio#12]
I might be doing something wrong - on creating new page...

```
`Radzen.Server.CompilationFailedException: error CS1705: Assembly 'Radzen.Server' with identity 'Radzen.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

at Radzen.Server.ProjectContext.Compile(Compilation compilation, AssemblyLoadContext context) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectContext.cs:line 120
at Radzen.Server.ProjectServer.CompileTemplate(String fileName, String source, RazorProjectEngine projectEngine, AssemblyLoadContext context) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 805
at Radzen.Server.ProjectServer.RenderTemplate[T](String path, String content, T model) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 188
at Radzen.Server.CodeGenerationTemplateGenerator1.GenerateAsync(ProjectServer server, String outputPath, String name, CancellationToken token) in /Users/korchev/github/radzen-next/Radzen.Server/CodeGeneratorService.cs:line 242 at Radzen.Server.CodeGenerationService.<>c__DisplayClass5_1.<<Generate>b__0>d.MoveNext() in /Users/korchev/github/radzen-next/Radzen.Server/CodeGeneratorService.cs:line 144
```

**Comment by akorchev** [comment]
This seems to happen when creating a new page in a .NET 5 application. We will investigate further.

**Comment by akorchev** [comment]
You can [download](https://www.radzen.com/blazor-studio/download/) the latest version - 1.0.0.preview.4 which should handle this issue.

**Comment by akorchev** [comment]
Should be solved in the latest version.  Let us know if the problem persists after updating to the latest version!
