### ISSUE TITLE
Blazor Wasm cannot create new Application

### ISSUE THREAD

**Issue by mharned73** [radzenhq/radzen-blazor-studio#122]
I am testing  some different features of Blazor Wasm.

1. I create a new project as a new Blazor Wasm project - I run project after creation it runs
2. i add blank page to client - I get error Radzen.Server.CompilationFailedException: E:\source\repos\SignalRTestToPlc\Client\_Imports.razor(11,19): error CS0146: Circular base type dependency involving 'SignalRTest' and 'SignalRTest'
E:\source\repos\SignalRTestToPlc\Client\_Imports.razor(12,19): error CS0146: Circular base type dependency involving 'SignalRTest' and 'SignalRTest'

   at Radzen.Server.ProjectContext.Compile(Compilation compilation, AssemblyLoadContext context)
   at Radzen.Server.ProjectContext.Compile(Compilation compilation)
   at Radzen.Server.ProjectServer.Compile(String fileName, String source, RazorProjectEngine projectEngine)
   at Radzen.Server.ProjectServer.CompilePage(String fileName, String source, RazorProjectEngine engine)
   at Radzen.Server.ProjectServer.Render(String fileName, String source, Boolean renderLayout)
   at Radzen.Server.ProgramController.Render(RenderRequest request)

**Comment by akorchev** [comment]
Hi @mharned73,

This isn't a known issue. Can you attach the app that is havimg this problem?

**Comment by mharned73** [comment]
Here is link to OneDrive folder
[?Folder icon] RadzenSignalRTest<https://cabezoncontrolsllc-my.sharepoint.com/:f:/g/personal/mark_harned_cabezonctrls_com/EmVOUVjtSuNDty3rTCfG9AEBcO4YirNE0l8J7vqtlmofOA?e=s9KQzj>
Thanks,
Mark Harned
Cabezon Controls LLC

**Comment by akorchev** [comment]
I think this happens because the page is named the same as the application. This creates a class SignalRTest in the namespace SignalRTest and leads to those errors that you are getting.
