### ISSUE TITLE
CRUD Scaffolding no longer generating files!

### ISSUE THREAD

**Issue by BetterView24** [radzenhq/radzen-blazor-studio#143]
I have updated to Radzen Blazor Studio 1.28.3 & registered.
The .NET 8 project that I have been working on for the last 2 weeks no longer lets me create proper CRUD Pages.
Steps:
1 - Click on "Data" & select current MS SQL connection.
2 - Select add new data tables to selection (Overwrite Existing files is also selected)
3. Config: Cascade delete & entity Framework query tracking are selected. --> Next
4. GENERATE PAGES CUR CRUD OPERATIONS, CRUD is selected --> Next

NOTE: I have previously selected "DataGrid inline Edit", but have deleted razor files as this did not work. (only showed values, but no way to edit or add new).

CRUD Scaffolding
Selected new data table from MS SQL (all show up properly)
All options under Configuration selected  except for:
 Export to Excel, Reload on optimistic concurrency
--> Finish...
>>> Only the main razor file is created, but no CRUD operations. Just a GRID to show the data.

Please Help!!

**Comment by BetterView24** [comment]
LOG FIle: - restart & try CRUD scaffolding.

[2024-07-04 13:51:12.052] [info]  Checking for update
[2024-07-04 13:51:12.884] [info]  Update for version 1.28.3 is not available (latest version: 1.28.3, downgrade is disallowed).
[2024-07-04 13:51:57.461] [error] Error: System.ArgumentOutOfRangeException: The requested line number 814 must be less than the number of lines 803. (Parameter 'Line')
   at Microsoft.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position)
   at Radzen.Server.TextRange.ToTextSpan(SyntaxTree syntaxTree)
   at Radzen.Server.ProjectServer.GetActions(String fileName, String source, TextRange range)
   at Radzen.Server.ProgramController.Actions(ActionRequest request)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)

**Comment by akorchev** [comment]
CRUD pages need the table to have a primary key defined.
