### ISSUE TITLE
Unable to Build New .NET 6 WASM App

### ISSUE THREAD

**Issue by nkrzewinski** [radzenhq/radzen-blazor-studio#2]
Hey guys, I'm really excited to explore this tool and see how it could help myself and my team out! 

I'm having some issues getting a project to build. When I opened an existing WASM app, I was unable to build due to issues with my Program.cs file. To make sure it wasn't just my existing project, I created **a brand new .NET 6 WASM app using the Visual Studio 2022 template**, and I receive the two following errors. These are the same ones I received when I opened my existing project.

`RadzenTesting\RadzenTesting\Program.cs (3,7): error cs0246: The type or namespace name 'RadzenTesting' could not be found (are you missing a using directive or assembly reference?)`
`RadzenTesting\RadzenTesting\App.cs (3,7): error cs0246: The type or namespace name 'RadzenTesting' could not be found (are you missing a using directive or assembly reference?)`

Is this a .NET 6 issue or is there additional configuration that needs to be completed?

**Comment by samuelw28** [comment]
I'm having the same issue with a new .NET 6 WASM app I made. I have no issue building and running the project in Visual Studio as well. This is the exception I get from the auto-generated log. However, I don't have this issue with any of my pre-existing projects.

`[2022-03-29 17:48:22.555] [error] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Radzen.Server.ProjectContext.ProcessFile(String fileName, String source, RazorProjectEngine projectEngine, Boolean designTime) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectContext.cs:line 180
   at Radzen.Server.ProjectServer.ParseDocument(String fileName, String source, RazorProjectEngine projectEngine, Boolean designTime, Boolean prepare) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 422
   at Radzen.Server.ProjectServer.GetMembers(String fileName, String filter) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 663
   at Radzen.Server.CompilerService.GetMembers(String filePath, String filter) in /Users/korchev/github/radzen-next/Radzen.Server/Compiler.cs:line 256
   at Radzen.Server.ProgramController.Members(MembersRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 171
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)`

**Comment by akorchev** [comment]
Does the problem happen with the [latest version](https://www.radzen.com/blazor-studio/download/)? If yes what .NET version do you have installed (you can get it with `dotnet --version`).

**Comment by nkrzewinski** [comment]
@akorchev This problem occurred with .NET 6.

**Comment by akorchev** [comment]
The latest version is 1.0.0.preview.4 and was released an hour ago.

**Comment by nkrzewinski** [comment]
@akorchev I appreciate the prompt response. After looking at some other issues I noticed you guys have been cranking out preview builds and I had not updated to the most recent one. After updating to preview.4 the issue appears to have resolved itself. Thanks for the help!
