### ISSUE TITLE
only projects without auth could be opened.

### ISSUE THREAD

**Issue by Otto404** [radzenhq/radzen-blazor-studio#20]
I created some blazer apps.
- dotnet new blazorwasm -o wasm1 -au individual -ho
- dotnet new blazorserver -o server1 -au individual 

First Error: the output could not be copied.
+ error cs8801: die lokale Variable oder die lokale Funktion "connectionString", die in einer Anweisung der obersten Ebene in diesem Kontext deklariert wurde, kann nicht verwendet werden.
means:
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));

if you chance the code to:
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));

the first obstracle could be passed.

Opening the index.razor leads to:

Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger`1[Microsoft.AspNetCore.Authorization.DefaultAuthorizationService]' while attempting to activate 'Microsoft.AspNetCore.Authorization.DefaultAuthorizationService'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Radzen.Server.RemoteRenderer.HandleException(Exception exception) in /Users/korchev/github/radzen-next/Radzen.Server/RemoteRenderer.cs:line 82
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment)
   at Radzen.Server.Router.OnRouteChanged(Object sender, RouteChangedEventArgs e) in /Users/korchev/github/radzen-next/Radzen.Server/Router.cs:line 56
   at Radzen.Server.RouterService.Route(Type component, Type defaultLayout) in /Users/korchev/github/radzen-next/Radzen.Server/RouterService.cs:line 19
   at Radzen.Server.CircuitHost.AddComponent(Type layout, Type page) in /Users/korchev/github/radzen-next/Radzen.Server/CircuitHost.cs:line 34
   at Radzen.Server.ProjectServer.Render(String fileName, String source) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 417
   at Radzen.Server.ProgramController.Render(RenderRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 306

only projects without auth could be opened. 

I'm using 

net 6.0.201
runtime: 6.03

**Comment by GeorgeStephens** [comment]
I'm seeing this also with projects created in visual studio. (New `Blazor Server App` -> `.NET 6.0 (Long-term support)` -> Authentication = `Individual Accounts`)

In short it seems that Radzen Blazor Studio doesn't like `var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");` while Visual Studio 2022 doesn't blink. I haven't tried VS Code.

As mentioned by @Otto404 if you comment out the line it complains about it works perfectly:
`//var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
builder.Services.AddDbContext<ApplicationDbContext>(options => 
options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));`

Default app:

![Screenshot (79)](https://user-images.githubusercontent.com/8162303/161420644-7882a590-2ece-46ca-aeee-27eecc977247.png)

Line Modified:

![Screenshot (80)](https://user-images.githubusercontent.com/8162303/161420668-e486a9aa-cfcb-4b0b-81d3-5c1516181b94.png)

That said I'm not 100% sure this is the only issue with top level statements in `program.cs` as in one of my test apps that has a bit more in `program.cs` it fails with `Exception has been thrown by the target of an invocation.`

I'm running preview 6 and net 6.0.201

**Comment by akorchev** [comment]
I confirm that there is an issue with those templates. We will provide support for them with the very next release.

**Comment by akorchev** [comment]
We have released Radzen Blazor Studio 1.0.0.preview.7 which should address this issue.
