### ISSUE TITLE
Exception thrown when trying to open a .razor page.

### ISSUE THREAD

**Issue by hampusWisest** [radzenhq/radzen-blazor-studio#22]
```
[2022-04-06 10:08:30.011] [error] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Radzen.Server.ProjectContext.ProcessFile(String fileName, String source, RazorProjectEngine projectEngine, Boolean designTime) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectContext.cs:line 180
   at Radzen.Server.ProjectServer.ParseDocument(String fileName, String source, RazorProjectEngine projectEngine, Boolean designTime, Boolean prepare) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 422
   at Radzen.Server.ProjectServer.GetMembers(String fileName, String filter) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 663
   at Radzen.Server.CompilerService.GetMembers(String filePath, String filter) in /Users/korchev/github/radzen-next/Radzen.Server/Compiler.cs:line 256
   at Radzen.Server.ProgramController.Members(MembersRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 171
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by akorchev** [comment]
Any further details?

**Comment by hampusWisest** [comment]
Sorry, just wanted to quickly dokument.

Here is more details,

* I´m trying to open a .razor page and all I get is "Radzen Blazor Studio is buidling your project.". 
![image](https://user-images.githubusercontent.com/63351366/161929927-0ff16421-8e2d-4e3b-af2a-49eef1964004.png)

* This goes on forever (Or more then I have patience for).
* When I click on "Data" it throws the exception abow.
![image](https://user-images.githubusercontent.com/63351366/161930035-3141593c-e4de-4f76-a714-6ab14a39e670.png)

**Comment by akorchev** [comment]
Are you using the latest version? It should no longer allow you to change the tabs while the project is building. We have also fixed a version with infinite "building". If you are using the latest - 1.0.0.preview.6 we would love to test with your project. You can send it to info@radzen.com.

**Comment by hampusWisest** [comment]
I get this in the log aswell when i start RBS
Where do i check the version number in RBS?
```
[2022-04-06 10:27:45.612] [info]  Checking for update
[2022-04-06 10:27:45.872] [error] Error: Error: No published versions on GitHub
    at Object.t.newError (C:\Program Files\Radzen Blazor Studio\resources\app.asar\dist\radzen.main.js:2:44077)
    at o.element (C:\Program Files\Radzen Blazor Studio\resources\app.asar\dist\radzen.main.js:2:49062)
    at t.GitHubProvider.getLatestVersion (C:\Program Files\Radzen Blazor Studio\resources\app.asar\dist\radzen.main.js:2:129116)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getUpdateInfoAndProvider (C:\Program Files\Radzen Blazor Studio\resources\app.asar\dist\radzen.main.js:2:86727)
    at async g.doCheckForUpdates (C:\Program Files\Radzen Blazor Studio\resources\app.asar\dist\radzen.main.js:2:87013)
```

**Comment by akorchev** [comment]
The error you are getting means that you don't have the latest version for sure (we no longer user github releases for distribution of RBS). Please download it again from our website: https://www.radzen.com/blazor-studio/download/

**Comment by hampusWisest** [comment]
Upgrading to 1.0.0-preview.6 fixed this problem.

F.Y.I, It was also a hidden process in the background running the same project and that may have factor for why the exceptions were thrown.
