### ISSUE TITLE
Unable to Drag&Drop Built-in InputNumber

### ISSUE THREAD

**Issue by yoshi1220** [radzenhq/radzen-blazor-studio#42]
I couldn't Drag&Drop InputNumber and bind property. Always Error occurs.

![image](https://user-images.githubusercontent.com/19341602/171142200-1f0c4ae6-0b42-42f7-a351-53b065e35745.png)
![image](https://user-images.githubusercontent.com/19341602/171142316-521c9759-e7fd-43ad-8804-542df8d908ab.png)

System.InvalidOperationException: InputNumber requires a cascading parameter of type EditContext. For example, you can use InputNumber inside an EditForm.
   at Microsoft.AspNetCore.Components.Forms.InputBase`1.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
--- End of stack trace from previous location ---
   at Radzen.Server.RemoteRenderer.HandleException(Exception exception) in /Users/korchev/github/radzen-next/Radzen.Server/RemoteRenderer.cs:line 82
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.HandleExceptionViaErrorBoundary(Exception error, ComponentState errorSourceOrNull)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Radzen.Server.RemoteRenderer.HandleException(Exception exception) in /Users/korchev/github/radzen-next/Radzen.Server/RemoteRenderer.cs:line 82
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment)
   at Radzen.Server.Router.OnRouteChanged(Object sender, RouteChangedEventArgs e) in /Users/korchev/github/radzen-next/Radzen.Server/Router.cs:line 57
   at Radzen.Server.RouterService.Route(Type component, Type defaultLayout) in /Users/korchev/github/radzen-next/Radzen.Server/RouterService.cs:line 19
   at Radzen.Server.CircuitHost.AddComponent(Type layout, Type page) in /Users/korchev/github/radzen-next/Radzen.Server/CircuitHost.cs:line 34
   at Radzen.Server.ProjectServer.Render(String fileName, String source) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 411
   at Radzen.Server.ProgramController.Render(RenderRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 325

**Comment by akorchev** [comment]
InputNumber should be put inside EditForm. Does it work if you try that?

**Comment by akorchev** [comment]
I wish that were possible. The InputNumber component will just throw an exception during rendering if not inside an EditForm.
