### ISSUE TITLE
Renderer errors with global usings

### ISSUE THREAD

**Issue by briddums** [radzenhq/radzen-blazor-studio#43]
If I try to use global usings statements from C# 10, the renderer throws an error when trying to open a Page.razor.

I usually put all my usings in my .csproj file and remove them from individual .cs files.

```
<ItemGroup>
	<Using Include="Radzen" />
	<using Include="Radzen.Blazor" />

	<Using Include="Microsoft.AspNetCore.Builder" />
	<Using Include="Microsoft.AspNetCore.Components" />
	<Using Include="Microsoft.AspNetCore.Components.Web" />
	<Using Include="Microsoft.EntityFrameworkCore" />
	<Using Include="Microsoft.EntityFrameworkCore.Storage" />
	<Using Include="Microsoft.Extensions.DependencyInjection" />
	<Using Include="Microsoft.Extensions.Hosting" />
	<Using Include="Microsoft.JSInterop" />
	<Using Include="System.Reflection" />
</ItemGroup>
```

When I do so I get the message "Page threw exception during rendering" and a lot of CS0246 errors:

```
error CS0246: The type or namespace name 'IJSRuntime' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'NavigationManager' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'DialogService' could not be found (are you missing a using directive or an assembly reference?)
...

   at Radzen.Server.ProjectContext.Compile(Compilation compilation, AssemblyLoadContext context) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectContext.cs:line 180
   at Radzen.Server.ProjectServer.Compile(String fileName, String source, RazorProjectEngine projectEngine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 782
   at Radzen.Server.ProjectServer.CompilePage(String fileName, String source, RazorProjectEngine engine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 319
   at Radzen.Server.ProjectServer.Render(String fileName, String source) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 413
   at Radzen.Server.ProgramController.Render(RenderRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 333

```

**Comment by akorchev** [comment]
Hi @briddums,

I couldn't reproduce the problem in a test project. Global usings seem to work as expected. Can you attach a project which fails as you are describing?

**Comment by akorchev** [comment]
Are you still experiencing this problem @briddums ?

**Comment by briddums** [comment]
I've created a test project at https://github.com/briddums/rzerror.

Open the project in Blazor Studio, double-click on Test.razor, the error will occur.

Running against preview.17.

I removed 5 using statements from Test.razor.cs and added them to RzError.csproj

**Comment by akorchev** [comment]
Thanks for the sample! I reproduced the problem and will investigate what's going on.

**Comment by akorchev** [comment]
Hi @briddums did you manage to get it working with the latest release of RBS?
