### ISSUE TITLE
Infering a MSSQL database without any tables

### ISSUE THREAD

**Issue by hampusWisest** [radzenhq/radzen-blazor-studio#48]
Issue:
Trying to create a database connection to a MSSQL database that does not contain any tables.

Fix:
Option 1
- If the database does not contain any tables then let the user know by showing a message in the UI and don´t allow the user to create the connection before the database contains tables.

Option 2
- If the database does not contain any tables then let the user know by showing a message and let the user create the connection and the service will be generated. When the database later contains tables the user can go and update the database connection with tables. 

Error when trying to create a connection to a database without any tables.

```
Index was outside the bounds of the array.
   at System.Array.GetFlattenedIndex(ReadOnlySpan`1 indices)
   at System.Array.GetValue(Int32 index)
   at System.Array.System.Collections.IList.get_Item(Int32 index)
   at Radzen.Server.TemplateConfig.<>c__DisplayClass51_0.<CreateScript>b__3(Rule r) in /Users/korchev/github/radzen-next/Radzen.Server/TemplateEngine.cs:line 564
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.UnionIterator`1.GetNext()
   at System.Linq.Enumerable.UnionIterator`1.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Radzen.Server.TemplateConfig.CreateScript(IDictionary`2 parameters) in /Users/korchev/github/radzen-next/Radzen.Server/TemplateEngine.cs:line 531
   at Radzen.Server.TemplateEngine.RunAsync(String source, String dest, Boolean overwrite, IDictionary`2 parameters, Project serverProject, Project clientProject) in /Users/korchev/github/radzen-next/Radzen.Server/TemplateEngine.cs:line 785
   at Radzen.Server.LoggerExtensions.MeasureAsync[T](ILogger logger, String name, Func`1 action) in /Users/korchev/github/radzen-next/Radzen.Server/Logger.cs:line 83
   at Radzen.Server.ProgramController.Generate(GenerateRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 397
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by akorchev** [comment]
Hi @hampusWisest!

Indeed we will add validation there as well. Best regards!
