### ISSUE TITLE
Cannot establish MySQL connection

### ISSUE THREAD

**Issue by sonatique** [radzenhq/radzen-blazor-studio#50]
Hello,
I just started a new project from scratch with Blazor Studio alpha.3. I cannot have "Infer database..." to work with MySQL server.
I double-triple checked that all details I entered in MySQL Connection dialog are correct, I have network connection, I tried with different dbs or users, etc. but whatever I do, I always get the error:

`Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 432
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 363
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 94
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 124
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 911
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 405
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 369
   at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(MySqlConnection connection)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.SetupMySqlOptions(DbConnection connection)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at Radzen.Server.DatabaseService.Infer(InferDatabaseRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/DatabaseService.cs:line 70
   at Radzen.Server.ProgramController.InferDatabase(InferDatabaseRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 494
   at lambda_method385(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)`

Please note that the exact same connection information works like a charm in regular Razden. 
Please also note that if I make an error on purpose in the server name, for instance, I get an expected "timeout error".

Am I the only one?
Thanks in adavance
![image_2022-07-01_111823536](https://user-images.githubusercontent.com/4331300/176865682-b3ae5aec-2789-4342-981f-dcc6f4cc5e6d.png)

**Comment by akorchev** [comment]
Hi @sonatique,

This is strange as RBS uses the same connection code as Radzen. Can you attach a screenshot showing the connection settings in Radzen and RBS?

**Comment by sonatique** [comment]
Hi @akorchev, thanks for your reply, here you go:

Working Razden:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4331300/176880956-4b8e4c4c-cce6-44da-867a-690fb02194d0.png">
which endup (after the intermediate step for configuring infer details) with this display showing everything is fine:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/4331300/176881304-b668bc04-dfe1-45e5-8f34-1895adc8af95.png">

Not working Razden Studio:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/4331300/176881089-56a456e9-1405-48fc-885d-c365498c3b07.png">
which end-up with the stack trace I already posted.

You have to believe me that the server name under the red strikethrough

**Comment by akorchev** [comment]
Indeed it has to be a comma in order for the connection string to work. Try entering `yourserver,11300`in RBS and it should work. We will address that with the next version of RBS.

**Comment by akorchev** [comment]
I just double checked and you are right. MySQL needs a special case for that. A custom port won't work in the current version of RBS.

**Comment by akorchev** [comment]
We released a new version (beta.4) which should support custom ports.

**Comment by sonatique** [comment]
Hello, thanks, indeed the connection can now be made, great! db is inferred and somes pages created but I get a lot of compilation errors while trying to run.... But that is a different story, I guess you're aware of this, given it's alpha. Let me know if you want details.

**Comment by akorchev** [comment]
Can you paste the code of Program.cs?

**Comment by sonatique** [comment]
Ho no, sorry, I think github did not properly handle "smaller than" "larger than" despite I used quote, sorry I didn't notice. The actual code is this:
![image](https://user-images.githubusercontent.com/4331300/177517685-83f817c6-45dd-4ed7-a062-7b8ade8dc73e.png)

**Comment by akorchev** [comment]
Thanks! I thought I was losing my mind :) I saw what the problem is though: `builder.builder.Configuration`. We will fix that soon.

**Comment by akorchev** [comment]
We released alpha.5 that should address the reported issue with having `builder.builder` in the generated code.

**Comment by sonatique** [comment]
@akorchev thanks, much better now! It's usable for further testing, great.
I just notice several warning regarding _"The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results. etc._" but I didn't look at the code yet.
Thanks
