### ISSUE TITLE
Page threw exception during rendering

### ISSUE THREAD

**Issue by mdchafin** [radzenhq/radzen-blazor-studio#6]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Radzen.Server.ProjectServer.ParseDocument(String fileName, String source, RazorProjectEngine projectEngine, Boolean designTime, Boolean prepare) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 466
   at Radzen.Server.ProjectServer.Compile(String fileName, String source, RazorProjectEngine projectEngine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 759
   at Radzen.Server.ProjectServer.CompilePage(String fileName, String source, RazorProjectEngine engine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 328
   at Radzen.Server.ProjectServer.Render(String fileName, String source) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 397
   at Radzen.Server.ProgramController.Render(RenderRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 305

**Comment by akorchev** [comment]
This looks as an issue that we may have fixed in the latest update. Please try the automatic update (restart Radzen Blazor Studio or click Check for updates in the Help menu item) or download it from here: https://www.radzen.com/blazor-studio/download/

**Comment by AnNormalie** [comment]
I had the same error in the log.txt file, after updating to `1.0.0-preview.2` it didn't occur anymore.

**Comment by mdchafin** [comment]
I just downloaded this from the email I was sent. Is the link not to the current version?

**Comment by mdchafin** [comment]
Downloaded and installed preview 3 no joy

System.NullReferenceException: Object reference not set to an instance of an object.
   at Radzen.Server.ProjectServer.ParseDocument(String fileName, String source, RazorProjectEngine projectEngine, Boolean designTime, Boolean prepare) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 466
   at Radzen.Server.ProjectServer.Compile(String fileName, String source, RazorProjectEngine projectEngine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 759
   at Radzen.Server.ProjectServer.CompilePage(String fileName, String source, RazorProjectEngine engine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 328
   at Radzen.Server.ProjectServer.Render(String fileName, String source) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 397
   at Radzen.Server.ProgramController.Render(RenderRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 305

**Comment by akorchev** [comment]
Can you attach a screenshot of the error? I feel it may be a different one. Ideally you can send us your application (if it is a private one you can send it to info@radzen.com). We don't need it to be running - just the code to troubleshoot.

**Comment by mdchafin** [comment]
See video at https://www.screencast.com/t/UtAttIkKji

**Comment by akorchev** [comment]
This video maybe shows a different issue - the building never ends. I believe we have addressed that. You can try with the latest version.
