### ISSUE TITLE
Not able to Scaffold with MSSQL  Database

### ISSUE THREAD

**Issue by ManthanManthan** [radzenhq/radzen-blazor-studio#65]
OS : Windows 11.
App: Blazor Server
Database :   Server SQL 2019 (Local Machine Server)   

DB server name : LAPTOP-MAB24UFD\MRTDBSRV

Successfully able to connect to database and fetch the tables and view... Create models and then shows the following error.

I am facing issue while Scaffolding with MSSQL database. Getting error :

-------------------------------------------------------------------------------------------------------------------------------------------
'M' is an invalid escapable character within a JSON string. The string should be correctly escaped. Path: $.ConnectionStrings | LineNumber: 2 | BytePositionInLine: 59.
 ---> System.Text.Json.JsonReaderException: 'M' is an invalid escapable character within a JSON string. The string should be correctly escaped. LineNumber: 2 | BytePositionInLine: 59.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(ReadOnlySpan`1 data, Int32 idx)
   at System.Text.Json.Utf8JsonReader.ConsumeString()
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Utf8JsonReader.TrySkip()
   at System.Text.Json.JsonDocument.TryParseValue(Utf8JsonReader& reader, JsonDocument& document, Boolean shouldThrow, Boolean useArrayPools)
   at System.Text.Json.Serialization.Converters.ObjectConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Radzen.Server.TemplateConfig.AddToSettings(Project project, ITemplateWriter writer, String code) in /Users/korchev/github/radzen-next/Radzen.Server/TemplateEngine.cs:line 716
   at Radzen.Server.TemplateConfig.ApplyTransformations(String source, Project serverProject, Project clientProject, ITemplateWriter writer, TemplateService templateService, ProjectServer server, ProjectServer client) in /Users/korchev/github/radzen-next/Radzen.Server/TemplateEngine.cs:line 391
   at Radzen.Server.TemplateEngine.RunAsync(String source, String dest, Boolean overwrite, IDictionary`2 parameters, Project serverProject, Project clientProject, ProjectServer server, ProjectServer client) in /Users/korchev/github/radzen-next/Radzen.Server/TemplateEngine.cs:line 1140
   at Radzen.Server.LoggerExtensions.MeasureAsync[T](ILogger logger, String name, Func`1 action) in /Users/korchev/github/radzen-next/Radzen.Server/Logger.cs:line 99
   at Radzen.Server.ProgramController.Generate(GenerateRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 413
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
-------------------------------------------------------------------------------------------------------------------------------------------

**Comment by ManthanManthan** [comment]
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*"
}

**Comment by akorchev** [comment]
Hi @ManthanManthan,

We just released beta.1 which should hopefully solve this issue. Thank you for reporting it!

**Comment by koksalbasar** [comment]
I've a smilar issue after installed beta 1.

Here are the error messages

**_The first error group likes this. Some parentheses are expected_**
`Code	Description	File	Line
CS1001	Identifier expected	C:\Users\Administrator\source\repos\BlazorTutorials\Tutorial2\Services\ValuraAppService.cs	101
CS1040	Preprocessor directives must appear as the first non-whitespace character on a line	C:\Users\Administrator\source\repos\BlazorTutorials\Tutorial2\Services\ValuraAppService.cs	101
CS1026	) expected	C:\Users\Administrator\source\repos\BlazorTutorials\Tutorial2\Services\ValuraAppService.cs	102
`

**_The second error group likes this. Some entities and properties are missing._**
`Code	Description	File	Line
CS0103	The name 'ıd' does not exist in the current context	C:\Users\Administrator\source\repos\BlazorTutorials\Tutorial2\Services\ValuraAppService.cs	105
CS0103	The name 'office' does not exist in the current context	C:\Users\Administrator\source\repos\BlazorTutorials\Tutorial2\Services\ValuraAppService.cs	165
CS0103	The name 'region' does not exist in the current context	C:\Users\Administrator\source\repos\BlazorTutorials\Tutorial2\Services\ValuraAppService.cs	347
CS0103	The name 'teammember' does not exist in the current context	C:\Users\Administrator\source\repos\BlazorTutorials\Tutorial2\Services\ValuraAppService.cs	535
`

**Comment by akorchev** [comment]
@koksalbasar 

Those are not known issues and we will need additional information.

**Comment by ManthanManthan** [comment]
Yes, It worked...Thx

**Comment by koksalbasar** [comment]
> Those are not known issues and we will need additional information.

Hi @akorchev,

Here are some notes about my issue,

*) I'm sure the RBS is the newest version. 1.0.0beta.1
*) I tried the same database on Radzen. And the solution is flawless.
*) On RBS I'm creating an application. (This app is up and running when I tested)
** Then I select and click the next button. That's all that I did.
** In addition I've tried standalone infer and then creating a CRUD page for one table. This is failed also.

How can I better document this issue for you? Can you show me the way?

@ManthanManthan 's issue is solved. Must I create a new one that referenced this issue?

**Comment by akorchev** [comment]
> Code Description File Line CS0103 The name 'ıd' does not exist in the current context 

This is most definitely the infamous "Turkish i" problem and we applied a fix for it. The other one - I am not sure. You can paste the generated code around the invalid line(s).

**Comment by koksalbasar** [comment]
This is the right point. 

I used "id" instead of "Id" and it worked.

I've not thought this kind of problem might occur, because Radzen already handles it.

I hope the next release work for both "I" and "i". 

Thanks much

**Comment by koksalbasar** [comment]
Hi @akorchev,

I want to give an update. I think this can be useful for the Turkish "I / i" problem.

I've retested the issue with a new table. The table is as follows.

```
[PKeyField] [int] NOT NULL, (**this is primary key**)
[Id] [nvarchar](128) NOT NULL,
[IdButNot] [nchar](10) NULL,
[hereisanothercapitalI] [nchar](10) NULL
```

Everything worked fine with this table.

The RBS is using the primary key's first letter to lowercase for the functions named Get**TableName**By**PrimaryKey**, Update**TableName** and Delete**TableName**. In Turkish the lowercase **"I"** is **"ı"** instead **"i"**. These two characters are different than each other. So end of this conversion we create a missing letter.

Maybe if you stop to convert for the first character of the primarykey from capital to lowercase then the issue will disappear.

**Comment by akorchev** [comment]
Should be fixed in latest version.

**Comment by koksalbasar** [comment]
I have bad news. Today I add an SQLite database to my project and the Id field is not worked again. 

If the field name would be id is working as before. 

MS SQL is working well.

**Comment by akorchev** [comment]
The latest version 1.0.4 should address this.
