### ISSUE TITLE
Building your project

### ISSUE THREAD

**Issue by DaCoder0** [radzenhq/radzen-blazor-studio#70]
first time use on a webassembly project

[2022-11-18 10:06:56.125] [info]  Checking for update
[2022-11-18 10:07:07.200] [error] Error: Error: net::ERR_NAME_NOT_RESOLVED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7167)
    at SimpleURLLoaderWrapper.emit (node:events:527:28)
[2022-11-18 10:07:08.627] [error] Error: System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.GetRelativePath(String relativeTo, String path, StringComparison comparisonType)
   at Radzen.Server.SolutionFacade.IsSubPathOf(String subPath, String basePath) in /Users/korchev/github/radzen-next/Radzen.Server/SolutionFacade.cs:line 87
   at Radzen.Server.SolutionFacade.ServerOf(String filePath) in /Users/korchev/github/radzen-next/Radzen.Server/SolutionFacade.cs:line 107
   at Radzen.Server.SolutionFacade.DispatchWhenReadyAsync[T](String filePath, Func`2 action) in /Users/korchev/github/radzen-next/Radzen.Server/SolutionFacade.cs:line 123
   at Radzen.Server.SolutionFacade.GetCultures(String fileName) in /Users/korchev/github/radzen-next/Radzen.Server/SolutionFacade.cs:line 366
   at Radzen.Server.ProgramController.Cultures(Request request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 410
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)

**Comment by akorchev** [comment]
Did you have a chance to try some of the more recent versions @DaCoder0?

**Comment by akorchev** [comment]
I am closing this issue due to inactivity. Please feel free to post updates.
