### ISSUE TITLE
RadzenTabs issues

### ISSUE THREAD

**Issue by koksalbasar** [radzenhq/radzen-blazor-studio#78]
RadzenTabs cannot switch between tabs when localize is enabled.
---
<img width="500px" alt="image" src="https://user-images.githubusercontent.com/56689928/204385869-fe7dbfcb-783f-4189-acfe-96626ecf5677.png">

The solution to the problem we discussed in #60 caused other problems.

1) I had been able to switch the tabs item when I clicked them before on the design time. But after the last update(1.0.4) this is not working if the tabs have some localization properties (I think).

 The SelectedIndex property of the RadzenTabs does not work. I settled the value to 0, 1, 2. nothing changed.

Changing the Selected property of the RadzenTabsItem also doesn't work in this case. 

2) When I change the selected property to true for the second tab the following error is thrown. This error did not throw into the first and the third tab items.
```
The best overloaded method match for 'Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<bool>(bool)' has some invalid arguments
   at CallSite.Target(Closure, CallSite, Type, Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at ValuraManager.Pages.AppSurveySetup.<BuildRenderTree>b__0_4(RenderTreeBuilder __builder4)
   at Radzen.Blazor.RadzenTabs.<BuildRenderTree>b__44_0(RenderTreeBuilder __builder2)
   at Microsoft.AspNetCore.Components.CascadingValue`1.Render(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at Radzen.Server.RemoteRenderer.HandleException(Exception exception) in /Users/korchev/github/radzen-next/Radzen.Server/RemoteRenderer.cs:line 82
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Radzen.Server.RemoteRenderer.HandleException(Exception exception) in /Users/korchev/github/radzen-next/Radzen.Server/RemoteRenderer.cs:line 82
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Radzen.Server.ProjectServer.Render(String fileName, String source) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 706
   at Radzen.Server.ProgramController.Render(RenderRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 454
```

Only one component can be added to the RadzenTabsItem
---
3) Only one component can be added to the RadzenTabsItem other than the first tab item. After adding a component inside the RadzenTabsItem the first tab is activated each time. For example, when you select the third tab item and add a row you cannot continue adding another component to the third tab because the first tab is activated immediately.

You can test the sample application. Please work with the page named AppSurveySetup.razor.

[RadzenTest4.zip](https://github.com/radzenhq/radzen-blazor-studio/files/10107965/RadzenTest4.zip)

**Comment by akorchev** [comment]
Unfortunately those issues are not related to #60. They are all caused by the implementation which toggles the selected tab by clicking it. To my regret it won't work in many cases and also leads to the side effects that you have observed (user cannot change tabs after the page is saved, current tab resets after adding a component etc.). 

We decided to disable that feature until we find a more robust implementation for it. Changing the tabs should happen as in Radzen 2.x - by setting the SelectedIndex property of RadzenTabs or the Selected property of RadzenTabsItem. We will make sure both work in your application.

**Comment by akorchev** [comment]
Update. The problem with being unable to set SelectedIndex and Selected is because there are components in the second tab that throw exceptions during rendering. Those are:

```
                        <RadzenButton ButtonStyle="ButtonStyle.Warning" Disabled="@isDisabledManager" Icon="edit" Size="ButtonSize.Small" style="float: none; margin-right: 5px" MouseEnter="@Button14MouseEnter" Click="@Button14Click">
                        </RadzenButton>
                        
                        <RadzenButton ButtonStyle="ButtonStyle.Danger" Disabled="@isDisabledManager" Icon="remove_circle_outline" Size="ButtonSize.Small" style="margin-right: 5px; vertical-align: middle" Visible="@(ManagerSurveyMailListResult.Count() == 0)" MouseEnter="@Button13MouseEnter" Click="@Button13Click">
                        </RadzenButton>
```

The problem with them is that they use the `isDisabledManager` property which is used as a `bool` but is of type `dynamic`. Radzen Blazor Studio does not support this case at the moment and fails to pick the correct default value for that property. Changing the type of the `isDisabledManager` property to `bool` should allow you to set SelectedIndex and Selected.
![selectedindex](https://user-images.githubusercontent.com/454726/204494152-09a643a9-1e75-4198-b2b6-cc4d3f892ab8.gif)

**Comment by koksalbasar** [comment]
Thank you @korchev it's worked and when the selectedIndex property is set the jumping issue is also resolved. You saved my life. Otherwise I have to write my codes manually :).

You can close this issue whenever you want.

PS. This was a good example of when the error raised where should I look and how should I think. Thank you.
