### ISSUE TITLE
RadzenDataGrid components Value (@bind-value) property returns an error

### ISSUE THREAD

**Issue by koksalbasar** [radzenhq/radzen-blazor-studio#79]
Hi Radzen Team,

The @Selected property that I created gives the following error when I try to add from GUI but it works when I add manually from the razor file.
```
C:\Users\Administrator\source\repos\Valura_v2\server\Pages\Tenant.razor(25,272): error CS1503: 1 argument: cannot convert from 'ValuraMasterApplication.Models.MasterData.Tenant' to 'System.Collections.Generic.IList<ValuraMasterApplication.Models.MasterData.Tenant>'
C:\Users\Administrator\source\repos\Valura_v2\server\Pages\Tenant.razor(197,377): error CS1503: 2 arguments: connat convert from 'Microsoft.AspNetCore.Components.EventCallback<ValuraMasterApplication.Models.MasterData.Tenant>' to 'Microsoft.AspNetCore.Components.EventCallback'

   at Radzen.Server.ProjectContext.Compile(Compilation compilation, AssemblyLoadContext context) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectContext.cs:line 173
   at Radzen.Server.ProjectContext.Compile(Compilation compilation) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectContext.cs:line 178
   at Radzen.Server.ProjectServer.Compile(String fileName, String source, RazorProjectEngine projectEngine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 1095
   at Radzen.Server.ProjectServer.CompilePage(String fileName, String source, RazorProjectEngine engine) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 451
   at Radzen.Server.ProjectServer.Render(String fileName, String source) in /Users/korchev/github/radzen-next/Radzen.Server/ProjectServer.cs:line 685
   at Radzen.Server.ProgramController.Render(RenderRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/ProgramController.cs:line 446
<RadzenImage Path="assets/images/valueco_icon_trans_mavi.png" style="width: 25%">, 1 of 1 found for 'grid0row', at 162:54
```

The error message disappears after manually adding. (After select other component)
<img width="464" alt="image" src="https://user-images.githubusercontent.com/56689928/204561870-b932ba7f-80cc-4635-84ed-b531203477af.png">

**Comment by akorchev** [comment]
What type is selectedTenant?

**Comment by koksalbasar** [comment]
I used your [Data Grid Single Selection](https://blazor.radzen.com/datagrid-single-selection) example

Grid data like this `protected IEnumerable<TenantModel> getTenantsResult`
and the selected item like this `protected IList<TenantModel> selectedTenant;`

**Comment by akorchev** [comment]
Thanks. Will be fixed with the next release.
